---
- name: Create service account for Statsite
  user: name=statsite
        system=yes
        home="{{ statsite_data_dir }}"
        shell=/bin/false
        state=present

- name: Ensure Statsite directories exist
  file: path="{{ item }}"
        state=directory
  with_items:
    - "{{ statsite_conf_dir }}"
    - "{{ statsite_sink_dir }}"

- name: Download Statsite
  get_url: url="https://github.com/armon/statsite/archive/v{{ statsite_version }}.tar.gz"
           dest="/usr/local/src/statsite-{{ statsite_version }}.tar.gz"

- name: Extract Statsite
  unarchive: src="/usr/local/src/statsite-{{ statsite_version }}.tar.gz"
             dest="/usr/local/src"
             copy=no

- name: Install SCons
  pip: name="SCons"
       extra_args="--egg --install-option --standard-lib"
       state=present

- name: Build Statsite
  command: "make"
  args:
    chdir: "/usr/local/src/statsite-{{ statsite_version }}"
    creates: "/usr/local/src/statsite-{{ statsite_version }}/statsite"
  register: installed_statsite

- name: Copy Statsite executables
  command: "cp {{ item.src }} {{ item.dest }}"
  when: installed_statsite|changed
  with_items:
    - { src: "/usr/local/src/statsite-{{ statsite_version }}/statsite", dest: "/usr/sbin" }
    - { src: "/usr/local/src/statsite-{{ statsite_version }}/sinks/cloudwatch.sh", dest: "{{ statsite_sink_dir }}" }
    - { src: "/usr/local/src/statsite-{{ statsite_version }}/sinks/graphite.py", dest: "{{ statsite_sink_dir }}" }
    - { src: "/usr/local/src/statsite-{{ statsite_version }}/sinks/influxdb.py", dest: "{{ statsite_sink_dir }}" }
    - { src: "/usr/local/src/statsite-{{ statsite_version }}/sinks/librato.py", dest: "{{ statsite_sink_dir }}" }
  notify:
    - Restart Statsite

- name: Configure Statsite
  template: src=statsite.cfg.j2
            dest="{{ statsite_conf_dir }}/statsite.cfg"
  notify:
    - Restart Statsite

- name: Configure Statsite service definition
  template: src=statsite.conf.j2 dest=/etc/init/statsite.conf
  notify:
    - Restart Statsite

- name: Touch log file if it does not exist
  copy: content="" dest="{{ statsite_log }}" force=no

- name: Set log file permissions
  file: path={{ statsite_log }} owner=statsite group=statsite mode=0644

- name: Configure Statsite log rotation
  template: src=logrotate_statsite.j2 dest=/etc/logrotate.d/statsite
